name: gomigrator CI

on:
  push:
    branches:
      - wip

env:
  GO111MODULE: "on"
  GOLANG_VERSION: "1.23.0"
  GOLANGCI_LINT_VERSION: v1.63.4

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GOLANG_VERSION }}

      - name: Check out code
        uses: actions/checkout@v3

      - name: Run linters
        run: make lint

      - name: Build binary
        run: make build

      - name: Run unit tests
        run: make test

      - name: Run integration tests
        run: make integration-test

      - name: Cleanup Docker containers
        run: docker-compose -f docker-compose.test.yml down -v
